name: Publish Package

on:
  push:
    branches: ['master']

jobs:
  package-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2

      - name: Publish package on npm
        run: npm publish